### ISSUE TITLE
License breach

### ISSUE THREAD

**Issue by 12345ieee** [trenta3/scherzi#2]
I wrote `spinmouse.sh` in good old 2013 (for the Darda, I guess, but I digress).

Now I find it here, without even a proper license, nor attribution. What a shame.

You'll all hear from my lawyers.

**Comment by trenta3** [comment]
As far as I remember it was given to me by E.P., who had the file lying around. I then forgot to mention you in the repository.
I apologize for my negligence. Please issue a pull request with the proper attribution and/or licence you would like it had been given or let me know if you prefer it being deleted from the repo.

**Comment by 12345ieee** [comment]
@epol is a goddamn thief.

Stronzate a parte, io di solito sbatto sempre una licenza vicino a ogni riga di codice che pubblico, per quanto cretino.
Magari una MIT sul repo a nome "UZ admin", o qualcosa del genere.

**Comment by trenta3** [comment]
Prima o poi lo faccio con tutto il codice del repo

**Comment by 12345ieee** [comment]
L'hai fatto davvero!
Chiudiamo questa roba, che mi vergogno ad averla aperta.
